camera:
  fx: 1448.91045629
  fy: 1452.78908048
  cx: 939.79704351
  cy: 532.86128726

# LiDAR â†’ Camera transform
extrinsic_matrix:  # 4x4 matrix
  - [0.99922, 0.0301048, -0.0103452, 0.013047]
  - [-0.0103764, 0.000621355, -0.999946, 0.0817428]
  - [-0.0300963, 0.999274, 0.00101626, 0.117341]
  - [0.0, 0.0, 0.0, 1.0]